CREATE TYPE "RoleName" AS ENUM ('ADMIN', 'AUTHORITY', 'NGO_COORDINATOR', 'VOLUNTEER', 'AFFECTED_INDIVIDUAL');
CREATE TYPE "DisasterType" AS ENUM ('FLOOD', 'EARTHQUAKE', 'FIRE', 'PANDEMIC', 'CYCLONE', 'LANDSLIDE', 'OTHER');
CREATE TYPE "Severity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE "DisasterStatus" AS ENUM ('ACTIVE', 'MONITORING', 'CONTAINED', 'RESOLVED');
CREATE TYPE "RequestStatus" AS ENUM ('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED');
CREATE TYPE "Priority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE "ResourceStatus" AS ENUM ('AVAILABLE', 'RESERVED', 'ALLOCATED', 'EXPIRED');
CREATE TYPE "TaskStatus" AS ENUM ('OPEN', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

CREATE TABLE "Role" ("id" TEXT NOT NULL, "name" "RoleName" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Role_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "phone" TEXT, "roleId" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "latitude" DOUBLE PRECISION, "longitude" DOUBLE PRECISION, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Disaster" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "type" "DisasterType" NOT NULL, "description" TEXT NOT NULL, "location" TEXT NOT NULL, "latitude" DOUBLE PRECISION NOT NULL, "longitude" DOUBLE PRECISION NOT NULL, "severity" "Severity" NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "status" "DisasterStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Disaster_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EmergencyRequest" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "disasterId" TEXT, "requestType" TEXT NOT NULL, "description" TEXT NOT NULL, "latitude" DOUBLE PRECISION NOT NULL, "longitude" DOUBLE PRECISION NOT NULL, "priority" "Priority" NOT NULL DEFAULT 'MEDIUM', "status" "RequestStatus" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "EmergencyRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Resource" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "category" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "location" TEXT NOT NULL, "latitude" DOUBLE PRECISION, "longitude" DOUBLE PRECISION, "provider" TEXT NOT NULL, "expiryDate" TIMESTAMP(3), "status" "ResourceStatus" NOT NULL DEFAULT 'AVAILABLE', "ngoId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Resource_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Shelter" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "address" TEXT NOT NULL, "latitude" DOUBLE PRECISION NOT NULL, "longitude" DOUBLE PRECISION NOT NULL, "capacity" INTEGER NOT NULL, "occupiedBeds" INTEGER NOT NULL DEFAULT 0, "contactPerson" TEXT NOT NULL, "phone" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Shelter_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Volunteer" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "skills" TEXT[], "phone" TEXT NOT NULL, "location" TEXT NOT NULL, "latitude" DOUBLE PRECISION, "longitude" DOUBLE PRECISION, "availability" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Volunteer_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Task" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "status" "TaskStatus" NOT NULL DEFAULT 'OPEN', "disasterId" TEXT, "emergencyRequestId" TEXT, "volunteerId" TEXT, "dueAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Task_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "channel" TEXT NOT NULL, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NGO" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "registrationNo" TEXT NOT NULL, "userId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "NGO_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "actorId" TEXT, "action" TEXT NOT NULL, "entity" TEXT NOT NULL, "entityId" TEXT, "metadata" JSONB, "ipAddress" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Role_name_key" ON "Role"("name");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_roleId_idx" ON "User"("roleId");
CREATE INDEX "User_email_idx" ON "User"("email");
CREATE INDEX "Disaster_status_severity_idx" ON "Disaster"("status", "severity");
CREATE INDEX "Disaster_latitude_longitude_idx" ON "Disaster"("latitude", "longitude");
CREATE INDEX "EmergencyRequest_status_priority_idx" ON "EmergencyRequest"("status", "priority");
CREATE INDEX "EmergencyRequest_userId_idx" ON "EmergencyRequest"("userId");
CREATE INDEX "EmergencyRequest_disasterId_idx" ON "EmergencyRequest"("disasterId");
CREATE INDEX "Resource_category_status_idx" ON "Resource"("category", "status");
CREATE INDEX "Resource_ngoId_idx" ON "Resource"("ngoId");
CREATE INDEX "Shelter_latitude_longitude_idx" ON "Shelter"("latitude", "longitude");
CREATE UNIQUE INDEX "Volunteer_userId_key" ON "Volunteer"("userId");
CREATE INDEX "Task_status_idx" ON "Task"("status");
CREATE INDEX "Task_volunteerId_idx" ON "Task"("volunteerId");
CREATE INDEX "Notification_userId_readAt_idx" ON "Notification"("userId", "readAt");
CREATE UNIQUE INDEX "NGO_registrationNo_key" ON "NGO"("registrationNo");
CREATE UNIQUE INDEX "NGO_userId_key" ON "NGO"("userId");
CREATE INDEX "AuditLog_actorId_idx" ON "AuditLog"("actorId");
CREATE INDEX "AuditLog_entity_entityId_idx" ON "AuditLog"("entity", "entityId");

ALTER TABLE "User" ADD CONSTRAINT "User_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmergencyRequest" ADD CONSTRAINT "EmergencyRequest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmergencyRequest" ADD CONSTRAINT "EmergencyRequest_disasterId_fkey" FOREIGN KEY ("disasterId") REFERENCES "Disaster"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Resource" ADD CONSTRAINT "Resource_ngoId_fkey" FOREIGN KEY ("ngoId") REFERENCES "NGO"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Volunteer" ADD CONSTRAINT "Volunteer_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_disasterId_fkey" FOREIGN KEY ("disasterId") REFERENCES "Disaster"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_emergencyRequestId_fkey" FOREIGN KEY ("emergencyRequestId") REFERENCES "EmergencyRequest"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_volunteerId_fkey" FOREIGN KEY ("volunteerId") REFERENCES "Volunteer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "NGO" ADD CONSTRAINT "NGO_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
